framework:
    cache:
        # Unique name for the app's cache (to prevent collision)
        prefix_seed: uptime_sentinel

        # Default pool for most things (Rate Limiter, etc.)
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            # Dedicated pool for rate limiting (good for isolation)
            cache.rate_limiter:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
