# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    telemetry_buffer_key: 'telemetry_buffer'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # repository bindings
    App\Monitoring\Domain\Repository\MonitorRepositoryInterface:
        alias: App\Monitoring\Infrastructure\Persistence\MonitorRepository

    App\Monitoring\Domain\Repository\AlertRuleRepositoryInterface:
        alias: App\Monitoring\Infrastructure\Persistence\AlertRuleRepository

    App\Monitoring\Domain\Repository\EscalationPolicyRepositoryInterface:
        alias: App\Monitoring\Infrastructure\Persistence\EscalationPolicyRepository

    App\Monitoring\Domain\Repository\NotificationTemplateRepositoryInterface:
        alias: App\Monitoring\Infrastructure\Persistence\NotificationTemplateRepository

    App\Monitoring\Domain\Repository\NotificationChannelRepositoryInterface:
        alias: App\Monitoring\Infrastructure\Persistence\NotificationChannelRepository

    # Redis Client for Monitoring Infrastructure
    redis_client:
        class: 'object'
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_URL)%'

    App\Monitoring\Infrastructure\Redis\RedisTelemetryBuffer:
        arguments:
            $redis: '@redis_client'
            $bufferKey: '%telemetry_buffer_key%'

    App\Monitoring\Infrastructure\Persistence\MonitorStateRepository:
        arguments:
            $redis: '@redis_client'

    App\Telemetry\Application\Service\TelemetryIngestor:
        arguments:
            $redis: '@redis_client'
            $bufferKey: '%telemetry_buffer_key%'

    # Native Symfony Rate Limiter Storage
    Symfony\Component\RateLimiter\Storage\StorageInterface:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments: ['@cache.rate_limiter']

    App\Monitoring\Application\Service\AlertNotificationService:
        arguments:
            $mailer: '@mailer.mailer'
            $mailerFrom: '%env(string:MAILER_FROM)%'
